export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAILED = "GET_WEATHER_FAILED";

export const GET_POSITION_BY_CITY_NAME_REQUEST =
  "GET_POSITION_BY_CITY_NAME_REQUEST";
export const GET_COORDINATES_BY_CITY_NAME_FAILED =
  "GET_COORDINATES_BY_CITY_NAME_FAILED";
